# fly.toml app configuration file generated for parkers-smartbrain on 2024-01-14T14:10:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app_name = "parkers-smartbrain"
app = "parkers-smartbrain"
primary_region = "atl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
