# fly.toml app configuration file generated for parkers-smartbrain on 2023-07-16T18:02:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "parkers-smartbrain"
primary_region = "atl"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
